### ISSUE TITLE
Avoiding function name collision

### ISSUE THREAD

**Issue by luffah** [JeHuiPark/github-co-author-vim-plugin#3]
Hello,

  Vim has thousands of plugins and the function names of this one are really common.

  In vim, you can name function with a domain to avoid to overwrite an existing function name.
  Just rename 'plugin.vim' to 'GitHubCoAuthor.vim' and prefix function with `GitHubCoAuthor#`.

**Comment by JeHuiPark** [comment]
Thanks for sharing new information you didn't know.
It will be included in the next fix.
